spring:
  datasource:
    url: jdbc:h2:file:~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate

mail:
  host: ${MAIL_HOST}              # SMTP 서버 주소
  port: ${MAIL_PORT}              # SMTP 서버 포트
  username: ${MAIL_USERNAME}      # 이메일 사용자 계정
  password: ${MAIL_PASSWORD}      # 이메일 사용자 비밀번호
  sender-email: ${MAIL_SENDER_EMAIL} # 사용자 이메일 주소

  properties:
    mail:
      smtp:
        connectiontimeout: ${MAIL_CONNECTIONTIMEOUT} # SMTP 연결 타임아웃 (밀리초 단위)
        timeout: ${MAIL_TIMEOUT}                     # SMTP 응답 타임아웃 (밀리초 단위)
        writetimeout: ${MAIL_WRITETIMEOUT}           # SMTP 쓰기 타임아웃 (밀리초 단위)

  data:
    redis:
      host: ${REDIS_HOST}         # Redis 서버 호스트
      port: ${REDIS_PORT}         # Redis 서버 포트
